// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CheckAliveOperation             OperationName = "CheckAlive"
	CheckReadyOperation             OperationName = "CheckReady"
	CreateAndroidInstanceOperation  OperationName = "CreateAndroidInstance"
	DeleteAndroidInstanceOperation  OperationName = "DeleteAndroidInstance"
	GetAndroidInstanceOperation     OperationName = "GetAndroidInstance"
	GetAssetOperation               OperationName = "GetAsset"
	ListAndroidInstancesV1Operation OperationName = "ListAndroidInstancesV1"
	ListAssetsOperation             OperationName = "ListAssets"
	PutAssetOperation               OperationName = "PutAsset"
)
