// Code generated by ogen, DO NOT EDIT.

package api

// CreateAndroidInstanceParams is parameters of createAndroidInstance operation.
type CreateAndroidInstanceParams struct {
	// Return after the instance is ready to connect.
	Wait OptBool
}

// DeleteAndroidInstanceParams is parameters of deleteAndroidInstance operation.
type DeleteAndroidInstanceParams struct {
	// Android instance ID, e.g. android_someid.
	ID string
}

// GetAndroidInstanceParams is parameters of getAndroidInstance operation.
type GetAndroidInstanceParams struct {
	// Android instance ID, e.g. android_someid.
	ID string
}

// GetAssetParams is parameters of getAsset operation.
type GetAssetParams struct {
	// Asset ID.
	AssetId string
	// Toggles whether a download URL should be included in the response.
	IncludeDownloadUrl OptBool
	// Toggles whether an upload URL should be included in the response.
	IncludeUploadUrl OptBool
}

// ListAndroidInstancesParams is parameters of listAndroidInstances operation.
type ListAndroidInstancesParams struct {
	// Region where the instance is scheduled on.
	Region OptString
	// State filter to apply to Android instances to return.
	State OptAndroidInstanceState
	// Labels filter to apply to Android instances to return.
	// Expects a comma-separated list of key=value pairs (e.g., env=prod,region=us-west).
	LabelSelector OptString
}

// ListAssetsParams is parameters of listAssets operation.
type ListAssetsParams struct {
	// Query by file md5.
	Md5Filter OptString
	// Query by file name.
	NameFilter OptString
	// Toggles whether a download URL should be included in the response.
	IncludeDownloadUrl OptBool
	// Toggles whether an upload URL should be included in the response.
	IncludeUploadUrl OptBool
}
