// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/url"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/uri"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// CheckAlive invokes checkAlive operation.
	//
	// Check if the server is alive.
	//
	// GET /livez
	CheckAlive(ctx context.Context) error
	// CheckReady invokes checkReady operation.
	//
	// Check if the server is ready.
	//
	// GET /readyz
	CheckReady(ctx context.Context) error
	// CreateAndroidInstance invokes createAndroidInstance operation.
	//
	// Create an Android instance.
	//
	// POST /v1/android_instances
	CreateAndroidInstance(ctx context.Context, request *AndroidInstanceCreate, params CreateAndroidInstanceParams) (*AndroidInstance, error)
	// DeleteAndroidInstance invokes deleteAndroidInstance operation.
	//
	// Delete Android instance with given name.
	//
	// DELETE /v1/android_instances/{id}
	DeleteAndroidInstance(ctx context.Context, params DeleteAndroidInstanceParams) error
	// GetAndroidInstance invokes getAndroidInstance operation.
	//
	// Get Android instance with given ID.
	//
	// GET /v1/android_instances/{id}
	GetAndroidInstance(ctx context.Context, params GetAndroidInstanceParams) (*AndroidInstance, error)
	// GetAsset invokes getAsset operation.
	//
	// Get the asset with given ID.
	//
	// GET /v1/assets/{assetId}
	GetAsset(ctx context.Context, params GetAssetParams) (*Asset, error)
	// ListAndroidInstances invokes listAndroidInstances operation.
	//
	// List Android instances belonging to given organization.
	//
	// GET /v1/android_instances
	ListAndroidInstances(ctx context.Context, params ListAndroidInstancesParams) ([]AndroidInstance, error)
	// ListAssets invokes listAssets operation.
	//
	// List organization's all assets with given filters. If none given, return all assets.
	//
	// GET /v1/assets
	ListAssets(ctx context.Context, params ListAssetsParams) ([]Asset, error)
	// PutAsset invokes putAsset operation.
	//
	// If organization already has a file with given md5 a new asset referencing the same file will be
	// created with given name.
	// If not, an upload URL will be returned where the uploaded file's md5 MUST match with the md5
	// provided in this request.
	// In all cases a signed download URL is returned but upload URL is returned only when you need to
	// upload, e.g.
	// we don't have the file in your organization folder.
	//
	// PUT /v1/assets
	PutAsset(ctx context.Context, request *AssetPut) (*Asset, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// CheckAlive invokes checkAlive operation.
//
// Check if the server is alive.
//
// GET /livez
func (c *Client) CheckAlive(ctx context.Context) error {
	_, err := c.sendCheckAlive(ctx)
	return err
}

func (c *Client) sendCheckAlive(ctx context.Context) (res *CheckAliveOK, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/livez"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCheckAliveResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CheckReady invokes checkReady operation.
//
// Check if the server is ready.
//
// GET /readyz
func (c *Client) CheckReady(ctx context.Context) error {
	_, err := c.sendCheckReady(ctx)
	return err
}

func (c *Client) sendCheckReady(ctx context.Context) (res *CheckReadyOK, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/readyz"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCheckReadyResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CreateAndroidInstance invokes createAndroidInstance operation.
//
// Create an Android instance.
//
// POST /v1/android_instances
func (c *Client) CreateAndroidInstance(ctx context.Context, request *AndroidInstanceCreate, params CreateAndroidInstanceParams) (*AndroidInstance, error) {
	res, err := c.sendCreateAndroidInstance(ctx, request, params)
	return res, err
}

func (c *Client) sendCreateAndroidInstance(ctx context.Context, request *AndroidInstanceCreate, params CreateAndroidInstanceParams) (res *AndroidInstance, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/android_instances"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "wait" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "wait",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Wait.Get(); ok {
				return e.EncodeValue(conv.BoolToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCreateAndroidInstanceRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCreateAndroidInstanceResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DeleteAndroidInstance invokes deleteAndroidInstance operation.
//
// Delete Android instance with given name.
//
// DELETE /v1/android_instances/{id}
func (c *Client) DeleteAndroidInstance(ctx context.Context, params DeleteAndroidInstanceParams) error {
	_, err := c.sendDeleteAndroidInstance(ctx, params)
	return err
}

func (c *Client) sendDeleteAndroidInstance(ctx context.Context, params DeleteAndroidInstanceParams) (res *DeleteAndroidInstanceOK, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/v1/android_instances/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeDeleteAndroidInstanceResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetAndroidInstance invokes getAndroidInstance operation.
//
// Get Android instance with given ID.
//
// GET /v1/android_instances/{id}
func (c *Client) GetAndroidInstance(ctx context.Context, params GetAndroidInstanceParams) (*AndroidInstance, error) {
	res, err := c.sendGetAndroidInstance(ctx, params)
	return res, err
}

func (c *Client) sendGetAndroidInstance(ctx context.Context, params GetAndroidInstanceParams) (res *AndroidInstance, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/v1/android_instances/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeGetAndroidInstanceResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetAsset invokes getAsset operation.
//
// Get the asset with given ID.
//
// GET /v1/assets/{assetId}
func (c *Client) GetAsset(ctx context.Context, params GetAssetParams) (*Asset, error) {
	res, err := c.sendGetAsset(ctx, params)
	return res, err
}

func (c *Client) sendGetAsset(ctx context.Context, params GetAssetParams) (res *Asset, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/v1/assets/"
	{
		// Encode "assetId" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "assetId",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.AssetId))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "includeDownloadUrl" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "includeDownloadUrl",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.IncludeDownloadUrl.Get(); ok {
				return e.EncodeValue(conv.BoolToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "includeUploadUrl" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "includeUploadUrl",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.IncludeUploadUrl.Get(); ok {
				return e.EncodeValue(conv.BoolToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeGetAssetResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListAndroidInstances invokes listAndroidInstances operation.
//
// List Android instances belonging to given organization.
//
// GET /v1/android_instances
func (c *Client) ListAndroidInstances(ctx context.Context, params ListAndroidInstancesParams) ([]AndroidInstance, error) {
	res, err := c.sendListAndroidInstances(ctx, params)
	return res, err
}

func (c *Client) sendListAndroidInstances(ctx context.Context, params ListAndroidInstancesParams) (res []AndroidInstance, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/android_instances"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "region" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "region",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Region.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "state" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "state",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.State.Get(); ok {
				return e.EncodeValue(conv.StringToString(string(val)))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "labelSelector" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "labelSelector",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.LabelSelector.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeListAndroidInstancesResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListAssets invokes listAssets operation.
//
// List organization's all assets with given filters. If none given, return all assets.
//
// GET /v1/assets
func (c *Client) ListAssets(ctx context.Context, params ListAssetsParams) ([]Asset, error) {
	res, err := c.sendListAssets(ctx, params)
	return res, err
}

func (c *Client) sendListAssets(ctx context.Context, params ListAssetsParams) (res []Asset, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/assets"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "md5Filter" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "md5Filter",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Md5Filter.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "nameFilter" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "nameFilter",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.NameFilter.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "includeDownloadUrl" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "includeDownloadUrl",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.IncludeDownloadUrl.Get(); ok {
				return e.EncodeValue(conv.BoolToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "includeUploadUrl" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "includeUploadUrl",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.IncludeUploadUrl.Get(); ok {
				return e.EncodeValue(conv.BoolToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeListAssetsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// PutAsset invokes putAsset operation.
//
// If organization already has a file with given md5 a new asset referencing the same file will be
// created with given name.
// If not, an upload URL will be returned where the uploaded file's md5 MUST match with the md5
// provided in this request.
// In all cases a signed download URL is returned but upload URL is returned only when you need to
// upload, e.g.
// we don't have the file in your organization folder.
//
// PUT /v1/assets
func (c *Client) PutAsset(ctx context.Context, request *AssetPut) (*Asset, error) {
	res, err := c.sendPutAsset(ctx, request)
	return res, err
}

func (c *Client) sendPutAsset(ctx context.Context, request *AssetPut) (res *Asset, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/assets"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodePutAssetRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodePutAssetResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
