// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
)

func (s *APIErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/APIError
type APIError struct {
	Message string `json:"message"`
	// Optional reason for the returned error to show more user-friendly errors.
	Reason OptAPIErrorReason `json:"reason"`
}

// GetMessage returns the value of Message.
func (s *APIError) GetMessage() string {
	return s.Message
}

// GetReason returns the value of Reason.
func (s *APIError) GetReason() OptAPIErrorReason {
	return s.Reason
}

// SetMessage sets the value of Message.
func (s *APIError) SetMessage(val string) {
	s.Message = val
}

// SetReason sets the value of Reason.
func (s *APIError) SetReason(val OptAPIErrorReason) {
	s.Reason = val
}

// Optional reason for the returned error to show more user-friendly errors.
type APIErrorReason string

const (
	APIErrorReasonNoSubscription          APIErrorReason = "NoSubscription"
	APIErrorReasonNoRemainingMinutes      APIErrorReason = "NoRemainingMinutes"
	APIErrorReasonConcurrencyLimitReached APIErrorReason = "ConcurrencyLimitReached"
)

// AllValues returns all APIErrorReason values.
func (APIErrorReason) AllValues() []APIErrorReason {
	return []APIErrorReason{
		APIErrorReasonNoSubscription,
		APIErrorReasonNoRemainingMinutes,
		APIErrorReasonConcurrencyLimitReached,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s APIErrorReason) MarshalText() ([]byte, error) {
	switch s {
	case APIErrorReasonNoSubscription:
		return []byte(s), nil
	case APIErrorReasonNoRemainingMinutes:
		return []byte(s), nil
	case APIErrorReasonConcurrencyLimitReached:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *APIErrorReason) UnmarshalText(data []byte) error {
	switch APIErrorReason(data) {
	case APIErrorReasonNoSubscription:
		*s = APIErrorReasonNoSubscription
		return nil
	case APIErrorReasonNoRemainingMinutes:
		*s = APIErrorReasonNoRemainingMinutes
		return nil
	case APIErrorReasonConcurrencyLimitReached:
		*s = APIErrorReasonConcurrencyLimitReached
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// APIErrorStatusCode wraps APIError with StatusCode.
type APIErrorStatusCode struct {
	StatusCode int
	Response   APIError
}

// GetStatusCode returns the value of StatusCode.
func (s *APIErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *APIErrorStatusCode) GetResponse() APIError {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *APIErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *APIErrorStatusCode) SetResponse(val APIError) {
	s.Response = val
}

// Ref: #/components/schemas/AndroidInstance
type AndroidInstance struct {
	Metadata AndroidInstanceMetadata `json:"metadata"`
	Spec     AndroidInstanceSpec     `json:"spec"`
	Status   AndroidInstanceStatus   `json:"status"`
}

// GetMetadata returns the value of Metadata.
func (s *AndroidInstance) GetMetadata() AndroidInstanceMetadata {
	return s.Metadata
}

// GetSpec returns the value of Spec.
func (s *AndroidInstance) GetSpec() AndroidInstanceSpec {
	return s.Spec
}

// GetStatus returns the value of Status.
func (s *AndroidInstance) GetStatus() AndroidInstanceStatus {
	return s.Status
}

// SetMetadata sets the value of Metadata.
func (s *AndroidInstance) SetMetadata(val AndroidInstanceMetadata) {
	s.Metadata = val
}

// SetSpec sets the value of Spec.
func (s *AndroidInstance) SetSpec(val AndroidInstanceSpec) {
	s.Spec = val
}

// SetStatus sets the value of Status.
func (s *AndroidInstance) SetStatus(val AndroidInstanceStatus) {
	s.Status = val
}

// Ref: #/components/schemas/AndroidInstanceCreate
type AndroidInstanceCreate struct {
	Metadata OptAndroidInstanceCreateMetadata `json:"metadata"`
	Spec     OptAndroidInstanceCreateSpec     `json:"spec"`
}

// GetMetadata returns the value of Metadata.
func (s *AndroidInstanceCreate) GetMetadata() OptAndroidInstanceCreateMetadata {
	return s.Metadata
}

// GetSpec returns the value of Spec.
func (s *AndroidInstanceCreate) GetSpec() OptAndroidInstanceCreateSpec {
	return s.Spec
}

// SetMetadata sets the value of Metadata.
func (s *AndroidInstanceCreate) SetMetadata(val OptAndroidInstanceCreateMetadata) {
	s.Metadata = val
}

// SetSpec sets the value of Spec.
func (s *AndroidInstanceCreate) SetSpec(val OptAndroidInstanceCreateSpec) {
	s.Spec = val
}

type AndroidInstanceCreateMetadata struct {
	DisplayName OptString                              `json:"displayName"`
	Labels      OptAndroidInstanceCreateMetadataLabels `json:"labels"`
}

// GetDisplayName returns the value of DisplayName.
func (s *AndroidInstanceCreateMetadata) GetDisplayName() OptString {
	return s.DisplayName
}

// GetLabels returns the value of Labels.
func (s *AndroidInstanceCreateMetadata) GetLabels() OptAndroidInstanceCreateMetadataLabels {
	return s.Labels
}

// SetDisplayName sets the value of DisplayName.
func (s *AndroidInstanceCreateMetadata) SetDisplayName(val OptString) {
	s.DisplayName = val
}

// SetLabels sets the value of Labels.
func (s *AndroidInstanceCreateMetadata) SetLabels(val OptAndroidInstanceCreateMetadataLabels) {
	s.Labels = val
}

type AndroidInstanceCreateMetadataLabels map[string]string

func (s *AndroidInstanceCreateMetadataLabels) init() AndroidInstanceCreateMetadataLabels {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

type AndroidInstanceCreateSpec struct {
	Clues []AndroidInstanceCreateSpecCluesItem `json:"clues"`
	// The region where the instance will be created. If not given, will be decided based on scheduling
	// clues
	// and availability.
	Region OptString `json:"region"`
	// After how many minutes of inactivity should the instance be terminated.
	// Example values 1m, 10m, 3h.
	// Default is 3m.
	// Providing "0" disables inactivity checks altogether.
	InactivityTimeout OptDuration `json:"inactivityTimeout"`
	// After how many minutes should the instance be terminated.
	// Example values 1m, 10m, 3h.
	// Default is "0" which means no hard timeout.
	HardTimeout   OptDuration                                  `json:"hardTimeout"`
	InitialAssets []AndroidInstanceCreateSpecInitialAssetsItem `json:"initialAssets"`
}

// GetClues returns the value of Clues.
func (s *AndroidInstanceCreateSpec) GetClues() []AndroidInstanceCreateSpecCluesItem {
	return s.Clues
}

// GetRegion returns the value of Region.
func (s *AndroidInstanceCreateSpec) GetRegion() OptString {
	return s.Region
}

// GetInactivityTimeout returns the value of InactivityTimeout.
func (s *AndroidInstanceCreateSpec) GetInactivityTimeout() OptDuration {
	return s.InactivityTimeout
}

// GetHardTimeout returns the value of HardTimeout.
func (s *AndroidInstanceCreateSpec) GetHardTimeout() OptDuration {
	return s.HardTimeout
}

// GetInitialAssets returns the value of InitialAssets.
func (s *AndroidInstanceCreateSpec) GetInitialAssets() []AndroidInstanceCreateSpecInitialAssetsItem {
	return s.InitialAssets
}

// SetClues sets the value of Clues.
func (s *AndroidInstanceCreateSpec) SetClues(val []AndroidInstanceCreateSpecCluesItem) {
	s.Clues = val
}

// SetRegion sets the value of Region.
func (s *AndroidInstanceCreateSpec) SetRegion(val OptString) {
	s.Region = val
}

// SetInactivityTimeout sets the value of InactivityTimeout.
func (s *AndroidInstanceCreateSpec) SetInactivityTimeout(val OptDuration) {
	s.InactivityTimeout = val
}

// SetHardTimeout sets the value of HardTimeout.
func (s *AndroidInstanceCreateSpec) SetHardTimeout(val OptDuration) {
	s.HardTimeout = val
}

// SetInitialAssets sets the value of InitialAssets.
func (s *AndroidInstanceCreateSpec) SetInitialAssets(val []AndroidInstanceCreateSpecInitialAssetsItem) {
	s.InitialAssets = val
}

type AndroidInstanceCreateSpecCluesItem struct {
	Kind     AndroidInstanceCreateSpecCluesItemKind `json:"kind"`
	ClientIp OptString                              `json:"clientIp"`
}

// GetKind returns the value of Kind.
func (s *AndroidInstanceCreateSpecCluesItem) GetKind() AndroidInstanceCreateSpecCluesItemKind {
	return s.Kind
}

// GetClientIp returns the value of ClientIp.
func (s *AndroidInstanceCreateSpecCluesItem) GetClientIp() OptString {
	return s.ClientIp
}

// SetKind sets the value of Kind.
func (s *AndroidInstanceCreateSpecCluesItem) SetKind(val AndroidInstanceCreateSpecCluesItemKind) {
	s.Kind = val
}

// SetClientIp sets the value of ClientIp.
func (s *AndroidInstanceCreateSpecCluesItem) SetClientIp(val OptString) {
	s.ClientIp = val
}

type AndroidInstanceCreateSpecCluesItemKind string

const (
	AndroidInstanceCreateSpecCluesItemKindClientIP AndroidInstanceCreateSpecCluesItemKind = "ClientIP"
)

// AllValues returns all AndroidInstanceCreateSpecCluesItemKind values.
func (AndroidInstanceCreateSpecCluesItemKind) AllValues() []AndroidInstanceCreateSpecCluesItemKind {
	return []AndroidInstanceCreateSpecCluesItemKind{
		AndroidInstanceCreateSpecCluesItemKindClientIP,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AndroidInstanceCreateSpecCluesItemKind) MarshalText() ([]byte, error) {
	switch s {
	case AndroidInstanceCreateSpecCluesItemKindClientIP:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AndroidInstanceCreateSpecCluesItemKind) UnmarshalText(data []byte) error {
	switch AndroidInstanceCreateSpecCluesItemKind(data) {
	case AndroidInstanceCreateSpecCluesItemKindClientIP:
		*s = AndroidInstanceCreateSpecCluesItemKindClientIP
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type AndroidInstanceCreateSpecInitialAssetsItem struct {
	Kind      AndroidInstanceCreateSpecInitialAssetsItemKind   `json:"kind"`
	Source    AndroidInstanceCreateSpecInitialAssetsItemSource `json:"source"`
	URL       OptString                                        `json:"url"`
	AssetName OptString                                        `json:"assetName"`
}

// GetKind returns the value of Kind.
func (s *AndroidInstanceCreateSpecInitialAssetsItem) GetKind() AndroidInstanceCreateSpecInitialAssetsItemKind {
	return s.Kind
}

// GetSource returns the value of Source.
func (s *AndroidInstanceCreateSpecInitialAssetsItem) GetSource() AndroidInstanceCreateSpecInitialAssetsItemSource {
	return s.Source
}

// GetURL returns the value of URL.
func (s *AndroidInstanceCreateSpecInitialAssetsItem) GetURL() OptString {
	return s.URL
}

// GetAssetName returns the value of AssetName.
func (s *AndroidInstanceCreateSpecInitialAssetsItem) GetAssetName() OptString {
	return s.AssetName
}

// SetKind sets the value of Kind.
func (s *AndroidInstanceCreateSpecInitialAssetsItem) SetKind(val AndroidInstanceCreateSpecInitialAssetsItemKind) {
	s.Kind = val
}

// SetSource sets the value of Source.
func (s *AndroidInstanceCreateSpecInitialAssetsItem) SetSource(val AndroidInstanceCreateSpecInitialAssetsItemSource) {
	s.Source = val
}

// SetURL sets the value of URL.
func (s *AndroidInstanceCreateSpecInitialAssetsItem) SetURL(val OptString) {
	s.URL = val
}

// SetAssetName sets the value of AssetName.
func (s *AndroidInstanceCreateSpecInitialAssetsItem) SetAssetName(val OptString) {
	s.AssetName = val
}

type AndroidInstanceCreateSpecInitialAssetsItemKind string

const (
	AndroidInstanceCreateSpecInitialAssetsItemKindApp AndroidInstanceCreateSpecInitialAssetsItemKind = "App"
)

// AllValues returns all AndroidInstanceCreateSpecInitialAssetsItemKind values.
func (AndroidInstanceCreateSpecInitialAssetsItemKind) AllValues() []AndroidInstanceCreateSpecInitialAssetsItemKind {
	return []AndroidInstanceCreateSpecInitialAssetsItemKind{
		AndroidInstanceCreateSpecInitialAssetsItemKindApp,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AndroidInstanceCreateSpecInitialAssetsItemKind) MarshalText() ([]byte, error) {
	switch s {
	case AndroidInstanceCreateSpecInitialAssetsItemKindApp:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AndroidInstanceCreateSpecInitialAssetsItemKind) UnmarshalText(data []byte) error {
	switch AndroidInstanceCreateSpecInitialAssetsItemKind(data) {
	case AndroidInstanceCreateSpecInitialAssetsItemKindApp:
		*s = AndroidInstanceCreateSpecInitialAssetsItemKindApp
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type AndroidInstanceCreateSpecInitialAssetsItemSource string

const (
	AndroidInstanceCreateSpecInitialAssetsItemSourceURL       AndroidInstanceCreateSpecInitialAssetsItemSource = "URL"
	AndroidInstanceCreateSpecInitialAssetsItemSourceAssetName AndroidInstanceCreateSpecInitialAssetsItemSource = "AssetName"
)

// AllValues returns all AndroidInstanceCreateSpecInitialAssetsItemSource values.
func (AndroidInstanceCreateSpecInitialAssetsItemSource) AllValues() []AndroidInstanceCreateSpecInitialAssetsItemSource {
	return []AndroidInstanceCreateSpecInitialAssetsItemSource{
		AndroidInstanceCreateSpecInitialAssetsItemSourceURL,
		AndroidInstanceCreateSpecInitialAssetsItemSourceAssetName,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AndroidInstanceCreateSpecInitialAssetsItemSource) MarshalText() ([]byte, error) {
	switch s {
	case AndroidInstanceCreateSpecInitialAssetsItemSourceURL:
		return []byte(s), nil
	case AndroidInstanceCreateSpecInitialAssetsItemSourceAssetName:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AndroidInstanceCreateSpecInitialAssetsItemSource) UnmarshalText(data []byte) error {
	switch AndroidInstanceCreateSpecInitialAssetsItemSource(data) {
	case AndroidInstanceCreateSpecInitialAssetsItemSourceURL:
		*s = AndroidInstanceCreateSpecInitialAssetsItemSourceURL
		return nil
	case AndroidInstanceCreateSpecInitialAssetsItemSourceAssetName:
		*s = AndroidInstanceCreateSpecInitialAssetsItemSourceAssetName
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type AndroidInstanceMetadata struct {
	ID             string                           `json:"id"`
	DisplayName    OptString                        `json:"displayName"`
	OrganizationId string                           `json:"organizationId"`
	CreatedAt      time.Time                        `json:"createdAt"`
	TerminatedAt   OptDateTime                      `json:"terminatedAt"`
	Labels         OptAndroidInstanceMetadataLabels `json:"labels"`
}

// GetID returns the value of ID.
func (s *AndroidInstanceMetadata) GetID() string {
	return s.ID
}

// GetDisplayName returns the value of DisplayName.
func (s *AndroidInstanceMetadata) GetDisplayName() OptString {
	return s.DisplayName
}

// GetOrganizationId returns the value of OrganizationId.
func (s *AndroidInstanceMetadata) GetOrganizationId() string {
	return s.OrganizationId
}

// GetCreatedAt returns the value of CreatedAt.
func (s *AndroidInstanceMetadata) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetTerminatedAt returns the value of TerminatedAt.
func (s *AndroidInstanceMetadata) GetTerminatedAt() OptDateTime {
	return s.TerminatedAt
}

// GetLabels returns the value of Labels.
func (s *AndroidInstanceMetadata) GetLabels() OptAndroidInstanceMetadataLabels {
	return s.Labels
}

// SetID sets the value of ID.
func (s *AndroidInstanceMetadata) SetID(val string) {
	s.ID = val
}

// SetDisplayName sets the value of DisplayName.
func (s *AndroidInstanceMetadata) SetDisplayName(val OptString) {
	s.DisplayName = val
}

// SetOrganizationId sets the value of OrganizationId.
func (s *AndroidInstanceMetadata) SetOrganizationId(val string) {
	s.OrganizationId = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *AndroidInstanceMetadata) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetTerminatedAt sets the value of TerminatedAt.
func (s *AndroidInstanceMetadata) SetTerminatedAt(val OptDateTime) {
	s.TerminatedAt = val
}

// SetLabels sets the value of Labels.
func (s *AndroidInstanceMetadata) SetLabels(val OptAndroidInstanceMetadataLabels) {
	s.Labels = val
}

type AndroidInstanceMetadataLabels map[string]string

func (s *AndroidInstanceMetadataLabels) init() AndroidInstanceMetadataLabels {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

type AndroidInstanceSpec struct {
	// The region where the instance will be created. If not given, will be decided based on scheduling
	// clues
	// and availability.
	Region string `json:"region"`
	// After how many minutes of inactivity should the instance be terminated.
	// Example values 1m, 10m, 3h.
	// Default is 3m.
	// Providing "0" disables inactivity checks altogether.
	InactivityTimeout time.Duration `json:"inactivityTimeout"`
	// After how many minutes should the instance be terminated.
	// Example values 1m, 10m, 3h.
	// Default is "0" which means no hard timeout.
	HardTimeout OptDuration `json:"hardTimeout"`
}

// GetRegion returns the value of Region.
func (s *AndroidInstanceSpec) GetRegion() string {
	return s.Region
}

// GetInactivityTimeout returns the value of InactivityTimeout.
func (s *AndroidInstanceSpec) GetInactivityTimeout() time.Duration {
	return s.InactivityTimeout
}

// GetHardTimeout returns the value of HardTimeout.
func (s *AndroidInstanceSpec) GetHardTimeout() OptDuration {
	return s.HardTimeout
}

// SetRegion sets the value of Region.
func (s *AndroidInstanceSpec) SetRegion(val string) {
	s.Region = val
}

// SetInactivityTimeout sets the value of InactivityTimeout.
func (s *AndroidInstanceSpec) SetInactivityTimeout(val time.Duration) {
	s.InactivityTimeout = val
}

// SetHardTimeout sets the value of HardTimeout.
func (s *AndroidInstanceSpec) SetHardTimeout(val OptDuration) {
	s.HardTimeout = val
}

// Ref: #/components/schemas/AndroidInstanceState
type AndroidInstanceState string

const (
	AndroidInstanceStateUnknown    AndroidInstanceState = "unknown"
	AndroidInstanceStateCreating   AndroidInstanceState = "creating"
	AndroidInstanceStateReady      AndroidInstanceState = "ready"
	AndroidInstanceStateTerminated AndroidInstanceState = "terminated"
)

// AllValues returns all AndroidInstanceState values.
func (AndroidInstanceState) AllValues() []AndroidInstanceState {
	return []AndroidInstanceState{
		AndroidInstanceStateUnknown,
		AndroidInstanceStateCreating,
		AndroidInstanceStateReady,
		AndroidInstanceStateTerminated,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AndroidInstanceState) MarshalText() ([]byte, error) {
	switch s {
	case AndroidInstanceStateUnknown:
		return []byte(s), nil
	case AndroidInstanceStateCreating:
		return []byte(s), nil
	case AndroidInstanceStateReady:
		return []byte(s), nil
	case AndroidInstanceStateTerminated:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AndroidInstanceState) UnmarshalText(data []byte) error {
	switch AndroidInstanceState(data) {
	case AndroidInstanceStateUnknown:
		*s = AndroidInstanceStateUnknown
		return nil
	case AndroidInstanceStateCreating:
		*s = AndroidInstanceStateCreating
		return nil
	case AndroidInstanceStateReady:
		*s = AndroidInstanceStateReady
		return nil
	case AndroidInstanceStateTerminated:
		*s = AndroidInstanceStateTerminated
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type AndroidInstanceStatus struct {
	State                AndroidInstanceState `json:"state"`
	AdbWebSocketUrl      OptString            `json:"adbWebSocketUrl"`
	EndpointWebSocketUrl OptString            `json:"endpointWebSocketUrl"`
	Token                string               `json:"token"`
}

// GetState returns the value of State.
func (s *AndroidInstanceStatus) GetState() AndroidInstanceState {
	return s.State
}

// GetAdbWebSocketUrl returns the value of AdbWebSocketUrl.
func (s *AndroidInstanceStatus) GetAdbWebSocketUrl() OptString {
	return s.AdbWebSocketUrl
}

// GetEndpointWebSocketUrl returns the value of EndpointWebSocketUrl.
func (s *AndroidInstanceStatus) GetEndpointWebSocketUrl() OptString {
	return s.EndpointWebSocketUrl
}

// GetToken returns the value of Token.
func (s *AndroidInstanceStatus) GetToken() string {
	return s.Token
}

// SetState sets the value of State.
func (s *AndroidInstanceStatus) SetState(val AndroidInstanceState) {
	s.State = val
}

// SetAdbWebSocketUrl sets the value of AdbWebSocketUrl.
func (s *AndroidInstanceStatus) SetAdbWebSocketUrl(val OptString) {
	s.AdbWebSocketUrl = val
}

// SetEndpointWebSocketUrl sets the value of EndpointWebSocketUrl.
func (s *AndroidInstanceStatus) SetEndpointWebSocketUrl(val OptString) {
	s.EndpointWebSocketUrl = val
}

// SetToken sets the value of Token.
func (s *AndroidInstanceStatus) SetToken(val string) {
	s.Token = val
}

// Ref: #/components/schemas/Asset
type Asset struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	// Returned only if there is a corresponding file uploaded already.
	MD5               OptString `json:"md5"`
	SignedUploadUrl   OptString `json:"signedUploadUrl"`
	SignedDownloadUrl OptString `json:"signedDownloadUrl"`
}

// GetID returns the value of ID.
func (s *Asset) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *Asset) GetName() string {
	return s.Name
}

// GetMD5 returns the value of MD5.
func (s *Asset) GetMD5() OptString {
	return s.MD5
}

// GetSignedUploadUrl returns the value of SignedUploadUrl.
func (s *Asset) GetSignedUploadUrl() OptString {
	return s.SignedUploadUrl
}

// GetSignedDownloadUrl returns the value of SignedDownloadUrl.
func (s *Asset) GetSignedDownloadUrl() OptString {
	return s.SignedDownloadUrl
}

// SetID sets the value of ID.
func (s *Asset) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Asset) SetName(val string) {
	s.Name = val
}

// SetMD5 sets the value of MD5.
func (s *Asset) SetMD5(val OptString) {
	s.MD5 = val
}

// SetSignedUploadUrl sets the value of SignedUploadUrl.
func (s *Asset) SetSignedUploadUrl(val OptString) {
	s.SignedUploadUrl = val
}

// SetSignedDownloadUrl sets the value of SignedDownloadUrl.
func (s *Asset) SetSignedDownloadUrl(val OptString) {
	s.SignedDownloadUrl = val
}

// Ref: #/components/schemas/AssetPut
type AssetPut struct {
	Name string `json:"name"`
}

// GetName returns the value of Name.
func (s *AssetPut) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *AssetPut) SetName(val string) {
	s.Name = val
}

// CheckAliveOK is response for CheckAlive operation.
type CheckAliveOK struct{}

// CheckReadyOK is response for CheckReady operation.
type CheckReadyOK struct{}

// DeleteAndroidInstanceOK is response for DeleteAndroidInstance operation.
type DeleteAndroidInstanceOK struct{}

// NewOptAPIErrorReason returns new OptAPIErrorReason with value set to v.
func NewOptAPIErrorReason(v APIErrorReason) OptAPIErrorReason {
	return OptAPIErrorReason{
		Value: v,
		Set:   true,
	}
}

// OptAPIErrorReason is optional APIErrorReason.
type OptAPIErrorReason struct {
	Value APIErrorReason
	Set   bool
}

// IsSet returns true if OptAPIErrorReason was set.
func (o OptAPIErrorReason) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAPIErrorReason) Reset() {
	var v APIErrorReason
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAPIErrorReason) SetTo(v APIErrorReason) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAPIErrorReason) Get() (v APIErrorReason, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAPIErrorReason) Or(d APIErrorReason) APIErrorReason {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAndroidInstanceCreateMetadata returns new OptAndroidInstanceCreateMetadata with value set to v.
func NewOptAndroidInstanceCreateMetadata(v AndroidInstanceCreateMetadata) OptAndroidInstanceCreateMetadata {
	return OptAndroidInstanceCreateMetadata{
		Value: v,
		Set:   true,
	}
}

// OptAndroidInstanceCreateMetadata is optional AndroidInstanceCreateMetadata.
type OptAndroidInstanceCreateMetadata struct {
	Value AndroidInstanceCreateMetadata
	Set   bool
}

// IsSet returns true if OptAndroidInstanceCreateMetadata was set.
func (o OptAndroidInstanceCreateMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAndroidInstanceCreateMetadata) Reset() {
	var v AndroidInstanceCreateMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAndroidInstanceCreateMetadata) SetTo(v AndroidInstanceCreateMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAndroidInstanceCreateMetadata) Get() (v AndroidInstanceCreateMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAndroidInstanceCreateMetadata) Or(d AndroidInstanceCreateMetadata) AndroidInstanceCreateMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAndroidInstanceCreateMetadataLabels returns new OptAndroidInstanceCreateMetadataLabels with value set to v.
func NewOptAndroidInstanceCreateMetadataLabels(v AndroidInstanceCreateMetadataLabels) OptAndroidInstanceCreateMetadataLabels {
	return OptAndroidInstanceCreateMetadataLabels{
		Value: v,
		Set:   true,
	}
}

// OptAndroidInstanceCreateMetadataLabels is optional AndroidInstanceCreateMetadataLabels.
type OptAndroidInstanceCreateMetadataLabels struct {
	Value AndroidInstanceCreateMetadataLabels
	Set   bool
}

// IsSet returns true if OptAndroidInstanceCreateMetadataLabels was set.
func (o OptAndroidInstanceCreateMetadataLabels) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAndroidInstanceCreateMetadataLabels) Reset() {
	var v AndroidInstanceCreateMetadataLabels
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAndroidInstanceCreateMetadataLabels) SetTo(v AndroidInstanceCreateMetadataLabels) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAndroidInstanceCreateMetadataLabels) Get() (v AndroidInstanceCreateMetadataLabels, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAndroidInstanceCreateMetadataLabels) Or(d AndroidInstanceCreateMetadataLabels) AndroidInstanceCreateMetadataLabels {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAndroidInstanceCreateSpec returns new OptAndroidInstanceCreateSpec with value set to v.
func NewOptAndroidInstanceCreateSpec(v AndroidInstanceCreateSpec) OptAndroidInstanceCreateSpec {
	return OptAndroidInstanceCreateSpec{
		Value: v,
		Set:   true,
	}
}

// OptAndroidInstanceCreateSpec is optional AndroidInstanceCreateSpec.
type OptAndroidInstanceCreateSpec struct {
	Value AndroidInstanceCreateSpec
	Set   bool
}

// IsSet returns true if OptAndroidInstanceCreateSpec was set.
func (o OptAndroidInstanceCreateSpec) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAndroidInstanceCreateSpec) Reset() {
	var v AndroidInstanceCreateSpec
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAndroidInstanceCreateSpec) SetTo(v AndroidInstanceCreateSpec) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAndroidInstanceCreateSpec) Get() (v AndroidInstanceCreateSpec, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAndroidInstanceCreateSpec) Or(d AndroidInstanceCreateSpec) AndroidInstanceCreateSpec {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAndroidInstanceMetadataLabels returns new OptAndroidInstanceMetadataLabels with value set to v.
func NewOptAndroidInstanceMetadataLabels(v AndroidInstanceMetadataLabels) OptAndroidInstanceMetadataLabels {
	return OptAndroidInstanceMetadataLabels{
		Value: v,
		Set:   true,
	}
}

// OptAndroidInstanceMetadataLabels is optional AndroidInstanceMetadataLabels.
type OptAndroidInstanceMetadataLabels struct {
	Value AndroidInstanceMetadataLabels
	Set   bool
}

// IsSet returns true if OptAndroidInstanceMetadataLabels was set.
func (o OptAndroidInstanceMetadataLabels) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAndroidInstanceMetadataLabels) Reset() {
	var v AndroidInstanceMetadataLabels
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAndroidInstanceMetadataLabels) SetTo(v AndroidInstanceMetadataLabels) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAndroidInstanceMetadataLabels) Get() (v AndroidInstanceMetadataLabels, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAndroidInstanceMetadataLabels) Or(d AndroidInstanceMetadataLabels) AndroidInstanceMetadataLabels {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAndroidInstanceState returns new OptAndroidInstanceState with value set to v.
func NewOptAndroidInstanceState(v AndroidInstanceState) OptAndroidInstanceState {
	return OptAndroidInstanceState{
		Value: v,
		Set:   true,
	}
}

// OptAndroidInstanceState is optional AndroidInstanceState.
type OptAndroidInstanceState struct {
	Value AndroidInstanceState
	Set   bool
}

// IsSet returns true if OptAndroidInstanceState was set.
func (o OptAndroidInstanceState) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAndroidInstanceState) Reset() {
	var v AndroidInstanceState
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAndroidInstanceState) SetTo(v AndroidInstanceState) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAndroidInstanceState) Get() (v AndroidInstanceState, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAndroidInstanceState) Or(d AndroidInstanceState) AndroidInstanceState {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDuration returns new OptDuration with value set to v.
func NewOptDuration(v time.Duration) OptDuration {
	return OptDuration{
		Value: v,
		Set:   true,
	}
}

// OptDuration is optional time.Duration.
type OptDuration struct {
	Value time.Duration
	Set   bool
}

// IsSet returns true if OptDuration was set.
func (o OptDuration) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDuration) Reset() {
	var v time.Duration
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDuration) SetTo(v time.Duration) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDuration) Get() (v time.Duration, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDuration) Or(d time.Duration) time.Duration {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
