// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/jx"

	"github.com/ogen-go/ogen/json"
)

// setDefaults set default value of fields.
func (s *AndroidInstanceCreateSpec) setDefaults() {
	{
		val, _ := json.DecodeDuration(jx.DecodeStr("\"3m\""))
		s.InactivityTimeout.SetTo(val)
	}
	{
		val, _ := json.DecodeDuration(jx.DecodeStr("\"0\""))
		s.HardTimeout.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *AndroidInstanceCreateSpecInitialAssetsItem) setDefaults() {
	{
		val := AndroidInstanceCreateSpecInitialAssetsItemKind("App")
		s.Kind = val
	}
	{
		val := AndroidInstanceCreateSpecInitialAssetsItemSource("URL")
		s.Source = val
	}
}

// setDefaults set default value of fields.
func (s *AndroidInstanceSpec) setDefaults() {
	{
		val, _ := json.DecodeDuration(jx.DecodeStr("\"3m\""))
		s.InactivityTimeout = val
	}
	{
		val, _ := json.DecodeDuration(jx.DecodeStr("\"0\""))
		s.HardTimeout.SetTo(val)
	}
}
